version: "3.1"

services:
  api:
    build: .
    volumes :
      - '.:/app'
    ports:  
      - 3000:8080
  misqldatabase:
    container_name: database
    image: mysql:5.7 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: my_store
      MYSQL_USER: usr
      MYSQL_PASSWORD: jkl
    # docker container exec -it database /bin/bash
    # -h database -u usr -p
    # ports:  
    #    - 3360:3306
    # expose: 
    #     - 3306